In [1]:
import pandas as pd
import numpy as np

In [2]:
np.set_printoptions(suppress=True, linewidth=100, precision=2)

In [3]:
raw_data_np = np.genfromtxt('loan-data.csv',delimiter=';',skip_header=1,autostrip=True)

In [4]:
raw_data_np

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [5]:
np.isnan(raw_data_np).sum()

88005

In [6]:
temporary_fill = np.nanmax(raw_data_np)+1
temporary_mean = np.nanmean(raw_data_np,axis=0)

C:\Users\hp\AppData\Local\Temp\ipykernel_3064\2154036395.py:2: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(raw_data_np,axis=0)


In [7]:
temporary_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [8]:
temporary_stats = np.array([np.nanmin(raw_data_np,axis=0),
                           temporary_mean,
                           np.nanmax(raw_data_np,axis=0)])

C:\Users\hp\AppData\Local\Temp\ipykernel_3064\3514126878.py:1: RuntimeWarning: All-NaN slice encountered
  temporary_stats = np.array([np.nanmin(raw_data_np,axis=0),
C:\Users\hp\AppData\Local\Temp\ipykernel_3064\3514126878.py:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data_np,axis=0)])


In [9]:
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [10]:
columns_strings = np.argwhere(np.isnan(temporary_mean)).squeeze()

In [11]:
columns_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [12]:
columns_numeric = np.argwhere(np.isnan(temporary_mean)==False).squeeze()

In [13]:
columns_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [14]:
loan_data_strings = np.genfromtxt('loan-data.csv',delimiter=';',skip_header=1,autostrip=True,usecols=columns_strings,dtype=str)

In [15]:
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [16]:
loan_data_numeric = np.genfromtxt('loan-data.csv',delimiter=';',skip_header=1,autostrip=True,usecols=columns_numeric,filling_values=temporary_fill,dtype=np.int32)

In [17]:
loan_data_numeric

array([[48010226,    35000,    35000,       13,     1184,     9452],
       [57693261,    30000,    30000, 68616520,      938,     4679],
       [59432726,    15000,    15000, 68616520,      494,     1969],
       ...,
       [50415990,    10000,    10000, 68616520, 68616520,     2185],
       [46154151, 68616520,    10000,       16,      354,     3199],
       [66055249,    10000,    10000, 68616520,      309,      301]])

In [18]:
header_full = np.genfromtxt('loan-data.csv',delimiter=';',skip_footer=raw_data_np.shape[0],autostrip=True,dtype=str)

In [19]:
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [20]:
header_strings,header_numeric = header_full[columns_strings],header_full[columns_numeric]

In [21]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [22]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [23]:
def checkpoint(filename,checkpoint_header,checkpoint_data):
    np.savez(filename,header=checkpoint_header,data=checkpoint_data)
    checkpoint_variable = np.load(filename+'.npz')
    return checkpoint_variable

In [24]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [25]:
header_strings[0] = 'issue_date'

In [26]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [27]:
loan_data_strings[:,0] = np.chararray.strip(loan_data_strings[:,0],'-15')

In [28]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [29]:
months = ['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

In [30]:
for i in range(13):
    loan_data_strings[:,0] = np.where(loan_data_strings[:,0]==months[i],i,loan_data_strings[:,0])

In [31]:
np.unique(loan_data_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [32]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [33]:
np.unique(loan_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [34]:
status = ['','Charged Off','Default','Late (31-120 days)']

In [35]:
loan_data_strings[:,1] = np.where(np.isin(loan_data_strings[:,1],status),1,0)

In [36]:
np.unique(loan_data_strings[:,1])

array(['0', '1'], dtype='<U69')

In [37]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [38]:
header_strings[2] = 'term_months'

In [39]:
np.unique(loan_data_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [40]:
loan_data_strings[:,2] = np.chararray.strip(loan_data_strings[:,2],' months')

In [41]:
loan_data_strings[:,2] = np.where(loan_data_strings[:,2]=='',60,loan_data_strings[:,2])

In [42]:
np.unique(loan_data_strings[:,2])

array(['36', '60'], dtype='<U69')

In [43]:
np.unique(loan_data_strings[:,2])

array(['36', '60'], dtype='<U69')

In [44]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [45]:
np.unique(loan_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [46]:
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [47]:
np.unique(loan_data_strings[:,4], return_counts=True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([514, 285, 278, 239, 323, 502, 509, 517, 530, 553, 494, 629, 567, 586, 564, 423, 391, 267,
        250, 255, 223, 235, 162, 171, 139, 114,  94,  52,  34,  43,  16,  19,  10,   3,   7,   2],
       dtype=int64))

In [48]:
for i in np.unique(loan_data_strings[:,3])[1:]:
    loan_data_strings[:,4] = np.where((loan_data_strings[:,4]=='')&(loan_data_strings[:,3]==i),i+'5',loan_data_strings[:,4])

In [49]:
np.unique(loan_data_strings[:,4],return_counts=True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [50]:
loan_data_strings[:,4] = np.where(loan_data_strings[:,4]=='','H5',loan_data_strings[:,4])

In [51]:
np.unique(loan_data_strings[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H5'], dtype='<U69')

In [52]:
header_strings = np.delete(header_strings,3)

In [53]:
loan_data_strings = np.delete(loan_data_strings,3,axis=1)

In [54]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [55]:
np.unique(loan_data_strings[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H5'], dtype='<U69')

In [56]:
keys = np.unique(loan_data_strings[:,3])

In [57]:
values = list(range(1,np.unique(loan_data_strings[:,3]).shape[0]+1))

In [58]:
values

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36]

In [59]:
dict_sub_grade = dict(zip(keys,values))

In [60]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H5': 36}

In [61]:
for i in (np.unique(loan_data_strings[:,3])):
    loan_data_strings[:,3] = np.where(loan_data_strings[:,3]==i,dict_sub_grade[i],loan_data_strings[:,3])

In [62]:
np.unique(loan_data_strings[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [63]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [64]:
np.unique(loan_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [65]:
status = ['','Not Verified']

In [66]:
loan_data_strings[:,4] = np.where(np.isin(loan_data_strings[:,4],status),1,0)

In [67]:
np.unique(loan_data_strings[:,4])

array(['0', '1'], dtype='<U69')

In [68]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [69]:
np.unique(loan_data_strings[:,5])

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=12606806',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=13026045',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=1312426', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8138291',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8214572',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=849994'], dtype='<U69')

In [70]:
loan_data_strings[:,5] = np.chararray.strip(loan_data_strings[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

In [71]:
np.unique(loan_data_strings[:,5])

array(['12606806', '13026045', '1312426', ..., '8138291', '8214572', '849994'], dtype='<U69')

In [72]:
loan_data_strings[:,5].astype(np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [73]:
loan_data_numeric[:,0].astype(np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [74]:
np.array_equal(loan_data_strings[:,5].astype(np.int32),loan_data_numeric[:,0].astype(np.int32))

True

In [75]:
header_strings = np.delete(header_strings,5)
loan_data_strings = np.delete(loan_data_strings,5,axis=1)

In [76]:
np.unique(loan_data_strings[:,5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [77]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [78]:
header_strings[5] = 'address_state'

In [79]:
np.unique(loan_data_strings[:,5],return_counts=True)

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27], dtype=int64))

In [80]:
states_name,states_counts = np.unique(loan_data_strings[:,5],return_counts=True)

In [81]:
states_count_sorted = np.argsort(-states_counts)
states_name[states_count_sorted],states_counts[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [82]:
states_west = np.array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ'])
states_south = np.array(['WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY'])
states_midwest = np.array(['KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK'])
states_east = np.array(['NE', 'SD', 'VT', 'ND', 'ME'])

In [83]:
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5],states_west),1,loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5],states_south),2,loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5],states_midwest),3,loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5],states_east),4,loan_data_strings[:,5])

In [84]:
np.unique(loan_data_strings[:,5])

array(['1', '2', '3', '4'], dtype='<U69')

In [85]:
loan_data_strings

array([['5', '0', '36', '13', '0', '1'],
       ['0', '0', '36', '5', '0', '1'],
       ['9', '0', '36', '10', '0', '1'],
       ...,
       ['6', '0', '36', '5', '0', '1'],
       ['4', '0', '36', '17', '0', '1'],
       ['12', '0', '36', '4', '1', '1']], dtype='<U69')

In [86]:
loan_data_strings = loan_data_strings.astype(np.int32)

In [87]:
loan_data_strings

array([[ 5,  0, 36, 13,  0,  1],
       [ 0,  0, 36,  5,  0,  1],
       [ 9,  0, 36, 10,  0,  1],
       ...,
       [ 6,  0, 36,  5,  0,  1],
       [ 4,  0, 36, 17,  0,  1],
       [12,  0, 36,  4,  1,  1]])

In [88]:
checkpoint_strings = checkpoint('checkpoint_strings',header_strings,loan_data_strings)

In [89]:
checkpoint_strings['header']

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'address_state'], dtype='<U19')

In [90]:
np.array_equal(loan_data_strings,checkpoint_strings['data'])

True

In [91]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [92]:
loan_data_numeric

array([[48010226,    35000,    35000,       13,     1184,     9452],
       [57693261,    30000,    30000, 68616520,      938,     4679],
       [59432726,    15000,    15000, 68616520,      494,     1969],
       ...,
       [50415990,    10000,    10000, 68616520, 68616520,     2185],
       [46154151, 68616520,    10000,       16,      354,     3199],
       [66055249,    10000,    10000, 68616520,      309,      301]])

In [93]:
np.isnan(loan_data_numeric).sum()

0

In [94]:
np.isin(loan_data_numeric,temporary_fill).sum()

8005

In [95]:
np.unique(loan_data_numeric[:,0])

array([  373332,   575239,   707689, ..., 68614880, 68615915, 68616519])

In [96]:
np.isin(loan_data_numeric[:,0],temporary_fill).sum()

0

In [97]:
temporary_stats[:,columns_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

In [98]:
loan_data_numeric[:,2] = np.where(loan_data_numeric[:,2]==temporary_fill,temporary_stats[0,columns_numeric[2]],
                                 loan_data_numeric[:,2])

In [99]:
np.isin(loan_data_numeric[:,2],temporary_fill).sum()

0

In [100]:
temporary_stats[0,columns_numeric[3]]

6.0

In [101]:
for i in [1,3,4,5]:
    loan_data_numeric[:,i] = np.where(loan_data_numeric[:,i]==temporary_fill,temporary_stats[0,columns_numeric[i]],
                                     loan_data_numeric[:,i])

In [102]:
np.isin(loan_data_numeric,temporary_fill).sum()

0

In [103]:
loan_data_numeric

array([[48010226,    35000,    35000,       13,     1184,     9452],
       [57693261,    30000,    30000,        6,      938,     4679],
       [59432726,    15000,    15000,        6,      494,     1969],
       ...,
       [50415990,    10000,    10000,        6,       31,     2185],
       [46154151,     1000,    10000,       16,      354,     3199],
       [66055249,    10000,    10000,        6,      309,      301]])

In [104]:
EUR_USD = np.genfromtxt('EUR-USD.csv',delimiter=',',skip_header=1,autostrip=True,usecols=3)

In [105]:
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [106]:
exchange_rate = loan_data_strings[:,0]

In [107]:
for i in range(13):
    exchange_rate = np.where(exchange_rate == i,EUR_USD[i-1],exchange_rate)

exchange_rate = np.where(exchange_rate==0,np.mean(EUR_USD),exchange_rate)
exchange_rate

array([1.1 , 1.09, 1.13, ..., 1.12, 1.11, 1.09])

In [108]:
exchange_rate.shape

(10000,)

In [109]:
exchange_rate = np.reshape(exchange_rate,(10000,1))

In [110]:
exchange_rate.shape

(10000, 1)

In [111]:
loan_data_numeric = np.hstack((loan_data_numeric,exchange_rate))

In [112]:
loan_data_numeric.shape

(10000, 7)

In [113]:
header_numeric = np.concatenate((header_numeric,np.array(['exchange_rate'])))

In [114]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [115]:
columns_dollars = [1,2,4,5]

In [116]:
for i in columns_dollars:
    loan_data_numeric = np.hstack((loan_data_numeric,np.reshape(loan_data_numeric[:,i]/loan_data_numeric[:,6] ,(10000,1))))

In [117]:
loan_data_numeric.shape

(10000, 11)

In [118]:
header_additional = [columns_name+'_USD' for columns_name in header_numeric[columns_dollars]]

In [119]:
header_additional

['loan_amnt_USD', 'funded_amnt_USD', 'installment_USD', 'total_pymnt_USD']

In [120]:
header_numeric = np.concatenate((header_numeric,header_additional))

In [121]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_USD', 'funded_amnt_USD', 'installment_USD', 'total_pymnt_USD'], dtype='<U19')

In [122]:
header_numeric[columns_dollars] = [columns_name+'_EUR' for columns_name in header_numeric[columns_dollars]]

In [123]:
header_numeric

array(['id', 'loan_amnt_EUR', 'funded_amnt_EUR', 'int_rate', 'installment_EUR', 'total_pymnt_EUR',
       'exchange_rate', 'loan_amnt_USD', 'funded_amnt_USD', 'installment_USD', 'total_pymnt_USD'],
      dtype='<U19')

In [124]:
final_index = [0,1,7,2,8,3,4,9,5,10,6]

In [125]:
header_numeric = header_numeric[final_index]

In [126]:
loan_data_numeric = loan_data_numeric[:,final_index]

In [127]:
loan_data_numeric[:,5]

array([13.,  6.,  6., ...,  6., 16.,  6.])

In [128]:
loan_data_numeric[:,5] = loan_data_numeric[:,5]/100

In [129]:
np.unique(loan_data_numeric[:,5])

array([0.06, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26,
       0.27, 0.28])

In [130]:
checkpoint_numeric = checkpoint('checkpoint_numeric',header_numeric,loan_data_numeric)

In [131]:
checkpoint_numeric['data']

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.  ,     8623.82,        1.1 ],
       [57693261.  ,    30000.  ,    27437.4 , ...,     4679.  ,     4279.32,        1.09],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.  ,     1749.3 ,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.  ,     1946.9 ,        1.12],
       [46154151.  ,     1000.  ,      899.74, ...,     3199.  ,     2878.27,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.  ,      275.29,        1.09]])

In [132]:
np.array_equal(checkpoint_numeric['data'],loan_data_numeric)

True

In [133]:
checkpoint_strings['header']

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'address_state'], dtype='<U19')

In [134]:
checkpoint_strings['data']

array([[ 5,  0, 36, 13,  0,  1],
       [ 0,  0, 36,  5,  0,  1],
       [ 9,  0, 36, 10,  0,  1],
       ...,
       [ 6,  0, 36,  5,  0,  1],
       [ 4,  0, 36, 17,  0,  1],
       [12,  0, 36,  4,  1,  1]])

In [135]:
checkpoint_numeric['header']

array(['id', 'loan_amnt_EUR', 'loan_amnt_USD', 'funded_amnt_EUR', 'funded_amnt_USD', 'int_rate',
       'installment_EUR', 'installment_USD', 'total_pymnt_EUR', 'total_pymnt_USD', 'exchange_rate'],
      dtype='<U19')

In [136]:
checkpoint_numeric['data']

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.  ,     8623.82,        1.1 ],
       [57693261.  ,    30000.  ,    27437.4 , ...,     4679.  ,     4279.32,        1.09],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.  ,     1749.3 ,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.  ,     1946.9 ,        1.12],
       [46154151.  ,     1000.  ,      899.74, ...,     3199.  ,     2878.27,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.  ,      275.29,        1.09]])

In [137]:
checkpoint_strings['data'].shape

(10000, 6)

In [138]:
checkpoint_numeric['data'].shape

(10000, 11)

In [139]:
loan_data = np.hstack((checkpoint_numeric['data'],checkpoint_strings['data']))

In [140]:
loan_data.shape

(10000, 17)

In [141]:
header_full = np.concatenate((checkpoint_numeric['header'],checkpoint_strings['header']))

In [142]:
header_full

array(['id', 'loan_amnt_EUR', 'loan_amnt_USD', 'funded_amnt_EUR', 'funded_amnt_USD', 'int_rate',
       'installment_EUR', 'installment_USD', 'total_pymnt_EUR', 'total_pymnt_USD', 'exchange_rate',
       'issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'address_state'], dtype='<U19')

In [143]:
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        0.  ,        1.  ],
       [57693261.  ,    30000.  ,    27437.4 , ...,        5.  ,        0.  ,        1.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        0.  ,        1.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        0.  ,        1.  ],
       [46154151.  ,     1000.  ,      899.74, ...,       17.  ,        0.  ,        1.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        1.  ,        1.  ]])

In [144]:
loan_data[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [145]:
np.argsort(loan_data[:,0])

array([2086, 4812, 2353, ..., 4935, 9388, 8415], dtype=int64)

In [146]:
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [147]:
loan_data[:,0]

array([  373332.,   575239.,   707689., ..., 68614880., 68615915., 68616519.])

In [148]:
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

In [149]:
loan_data = np.vstack((header_full,loan_data))

In [150]:
loan_data

array([['id', 'loan_amnt_EUR', 'loan_amnt_USD', ..., 'sub_grade', 'verification_status',
        'address_state'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '1.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '25.0', '0.0', '1.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '0.0', '2.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '0.0', '3.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '1.0', '1.0']], dtype='<U32')

In [151]:
np.savetxt('loan_data_preprocessed.csv',loan_data,delimiter=',',fmt="%s")